### ISSUE TITLE
Unable to execute command on pimcore 6

### ISSUE THREAD

**Issue by ab-kily** [elements-at/ExportToolkit#4]
Hello and thank you for such a great plugin ) 

I have installed all bundles and have configured some of export settings. Unfortunately, I'm experiencing problem trying to execute command:

```bash
# /srv/www/htdocs/bin/console export-toolkit:export --config-name="KilyCMS"
There are no commands defined in the "export-toolkit" namespace.  
```
It seems, that ExportCommand have not installed correctly. It it possible to fix this issue without reinstalling bundle?

**Comment by ab-kily** [comment]
I've got it working by registering the command manually:
```bash
# cat app/config/services.yml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Elements\Bundle\ExportToolkitBundle\Command\ExportCommand:
        public: true
        autoconfigure: true
        tags:
            - { name: 'console.command', command: 'export-toolkit:export' }
```
But I think it would be better if the command will be registered automatically.

**Comment by fashxp** [comment]
hi, could you provide a PR? 
thank you

**Comment by ab-kily** [comment]
> hi, could you provide a PR?
> thank you

Unfortunately, I don't know this framework enough to make the changes look good. But I'll try )

**Comment by fashxp** [comment]
just add a service definition as you did in the comment above [here](https://github.com/elements-at/ExportToolkit/blob/master/src/Elements/Bundle/ExportToolkitBundle/Resources/config/services.yml) :)
